import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Sparkles, Bookmark, X, Loader2, Info } from "lucide-react";
import { toast } from "sonner";
import RecModal from "@/components/RecModal";
import ModelPicker from "@/components/ModelPicker";
import WatchlistButton from "@/components/WatchlistButton";
import FeedbackChips from "@/components/FeedbackChips";
import { RecPosterActions, POSTER_GRID, MatchStat, RatingStat } from "@/components/ApproveRejectOverlay";
import { DEFAULT_MODEL, providerLabel, notifyUsage } from "@/lib/models";

export default function Recommendations() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(false);
  const [active, setActive] = useState(null);
  const [model, setModel] = useState(DEFAULT_MODEL);

  const load = async () => {
    const r = await api.get("/recommendations");
    setItems(r.data);
  };

  useEffect(() => {
    load();
    api.get("/connections").then(r => r.data.ollama_model && setModel(r.data.ollama_model)).catch(() => {});
  }, []);

  const generate = async () => {
    setLoading(true);
    try {
      const r = await api.post("/recommendations/generate", { model });
      toast.success(`${r.data.count} picks via ${providerLabel(r.data.provider, r.data.model)}`);
      notifyUsage();
      await load();
    } catch { toast.error("Generation failed"); }
    finally { setLoading(false); }
  };

  const save = async (id) => {
    await api.post(`/recommendations/${id}/save`);
    setItems(list => list.map(r => r.id === id ? { ...r, saved: !r.saved } : r));
    toast.success("Saved to library");
  };

  const dismiss = async (id) => {
    await api.post(`/recommendations/${id}/dismiss`);
    setItems(list => list.filter(r => r.id !== id));
    toast("Dismissed");
  };

  const removeFromList = (id) => {
    setItems(list => list.filter(r => r.id !== id));
    setActive(a => (a && a.id === id ? null : a));
  };

  const markWatchlisted = (id) => {
    setItems(list => list.map(r => r.id === id ? { ...r, in_watchlist: true } : r));
    setActive(a => a && a.id === id ? { ...a, in_watchlist: true } : a);
  };

  const markApproved = (id) => {
    setItems(list => list.map(r => r.id === id ? { ...r, in_library: true } : r));
    setActive(a => a && a.id === id ? { ...a, in_library: true } : a);
  };

  const handleFeedback = (id, action) => {
    if (action === "hide" || action === "blacklist" || action === "watched") {
      setItems(list => list.filter(r => r.id !== id));
      setActive(null);
    }
  };

  return (
    <div className="px-1 sm:px-2 pb-4 float-in">
      <div className="flex items-start justify-between gap-4 mb-10">
        <div>
          <span className="chip chip-rose mb-4">AI Picks</span>
          <h1 className="font-display text-4xl sm:text-5xl font-extrabold tracking-tight">Curated for you</h1>
          <p className="text-slate-400 mt-2 max-w-xl">Every recommendation comes with a <em>reason</em> — generated by local Ollama <span className="text-[#EBD3A3]">qwen3:14b</span>. Open any card for a live deep-dive on why it fits you.</p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <ModelPicker value={model} onChange={setModel} disabled={loading} testid="recs-model-picker" />
          <button data-testid="generate-recommendations-button" onClick={generate} disabled={loading} className="glass-strong px-5 py-2.5 rounded-full text-sm font-medium flex items-center gap-2 hover:brutal-shadow-rose transition-shadow">
            {loading ? <Loader2 className="w-4 h-4 animate-spin"/> : <Sparkles className="w-4 h-4"/>}
            {loading ? "Generating…" : "New picks"}
          </button>
        </div>
      </div>

      <div className={`${POSTER_GRID}`}>
        {items.map((r, i) => (
          <RecCard key={r.id} rec={r} onSave={save} onDismiss={dismiss} onRejected={removeFromList} onWatchlist={markWatchlisted} onApproved={markApproved} onFeedback={handleFeedback} onOpen={() => setActive(r)} index={i} />
        ))}
      </div>

      {!items.length && (
        <div className="glass rounded-2xl p-16 text-center">
          <Sparkles className="w-10 h-10 mx-auto text-slate-600 mb-4" />
          <p className="text-slate-400">No recommendations yet — click <span className="text-white font-medium">New picks</span>.</p>
        </div>
      )}

      {active && <RecModal rec={active} model={model} onClose={() => setActive(null)} onSave={save} onWatchlist={markWatchlisted} onApproved={markApproved} onFeedback={handleFeedback} onDismiss={removeFromList} />}
    </div>
  );
}

function RecCard({ rec, onSave, onDismiss, onRejected, onWatchlist, onApproved, onFeedback, onOpen, index }) {
  return (
    <div data-testid={`movie-card-${rec.id}`} className="group relative float-in" style={{ animationDelay: `${index * 60}ms` }}>
      <div className="poster-frame relative rounded-2xl">
        <img src={rec.poster} alt={rec.title} className="aspect-[2/3] w-full object-cover poster-hover" />
        <div className="absolute top-3 left-3 z-10 flex flex-col items-start gap-1.5">
          <MatchStat score={rec.match_score} />
          <RatingStat rating={rec.tmdb_rating} />
        </div>
        <RecPosterActions rec={rec} onApproved={onApproved} onRejected={onRejected} />
        <div className="absolute top-[9.75rem] inset-x-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center gap-2 z-20">
          <button data-testid={`save-recommendation-button-${rec.id}`} onClick={(e)=>{e.stopPropagation(); onSave(rec.id);}} className={`flex-1 rounded-lg px-3 py-2 text-xs font-medium flex items-center justify-center gap-1.5 transition-colors ${rec.saved ? "bg-rose-500 text-white" : "bg-white/10 backdrop-blur hover:bg-white/20"}`}>
            <Bookmark className={`w-3.5 h-3.5 ${rec.saved ? "fill-current" : ""}`}/> {rec.saved ? "Saved" : "Save"}
          </button>
          <button data-testid={`info-recommendation-button-${rec.id}`} onClick={onOpen} className="rounded-lg px-3 py-2 bg-white/10 backdrop-blur hover:bg-white/20 transition-colors">
            <Info className="w-3.5 h-3.5"/>
          </button>
          <WatchlistButton rec={rec} onDone={onWatchlist} />
          <button data-testid={`dismiss-recommendation-button-${rec.id}`} onClick={(e)=>{e.stopPropagation(); onDismiss(rec.id);}} className="rounded-lg px-3 py-2 bg-white/10 backdrop-blur hover:bg-rose-500 transition-colors">
            <X className="w-3.5 h-3.5"/>
          </button>
        </div>
      </div>
      <div className="mt-3">
        <div className="flex items-baseline justify-between gap-2">
          <h3 className="font-display font-bold text-xl line-clamp-1">{rec.title}</h3>
          <span className="font-mono text-xs text-slate-500 shrink-0">{rec.year}</span>
        </div>
        <div className="flex flex-wrap gap-1 mt-1.5">
          {rec.genres?.slice(0, 2).map((g, i) => <span key={i} className="text-[10px] font-mono uppercase tracking-wider text-slate-500">{g}{i < Math.min(rec.genres.length,2)-1 ? " ·" : ""}</span>)}
        </div>
        <div className="mt-2">
          <FeedbackChips rec={rec} onFeedback={onFeedback} />
        </div>
      </div>
    </div>
  );
}
